### ISSUE TITLE
change CMake file

### ISSUE THREAD

**Issue by DariaWelt** [DenysRisukhin/ArcanoidDemo#1]
Здравствуйте.

В CMake файле не изменены подключаемые sourse файлы. При создании cocos new там по дефолту прописаны cpp: Classes/AppDelegate.cpp Classes/HelloWorldScene.cpp и соответствующие h файлы. Вы реализовали свою структуру папок в classes и добавили sourse для собственно реализации игры, но при скачивании архива с этого репозитория и запуска CMake проект не строится правильно и не собирается. 

Измените CMake файл в соответствии с теми файлами, которые должны быть подключены к проекту после сборки, для людей, которые в будущем будут смотреть и изучать вашу реализацию

Спасибо!

**Comment by DenysRisukhin** [comment]
Здравствуйте. Игру не делал крос платформ. Только под мак и ios. Возможно в
будущем обновлю. Thx
